Ejercicio con numpy 

Paso 1: Crear Arrays con Datos de Ventas

Usa la librería numpy para crear los siguientes arrays: meses: un array con los nombres de los meses del año. ventas_A, ventas_B, ventas_C: arrays que representan las ventas mensuales de tres productos diferentes.

In [2]:
import numpy as np
print("Lbrería importada.")

Lbrería importada.


In [3]:
# Paso 1: Crear arrays con datos de ventas mensuales
meses = np.array(['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])
ventas_A = np.array([150, 200, 250, 300, 220, 210, 180, 190, 230, 240, 280, 300])
ventas_B = np.array([180, 210, 230, 250, 270, 260, 240, 250, 270, 290, 310, 330])
ventas_C = np.array([200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420])
print("Todo listo...")

Todo listo...


Paso 2: Estadísticas Básicas

Calcula la media y la suma de ventas para los productos A, B y C usando las funciones de NumPy.
Imprime estos valores en el formato siguiente:
Media de ventas Producto A: <valor>
Suma de ventas Producto A: <valor>
Repite para los productos B y C.

In [4]:
#Suma de ventas
suma_producto_A = ventas_A.cumsum()[-1]
suma_producto_B = ventas_B.cumsum()[-1]
suma_producto_C = ventas_C.cumsum()[-1]

print(suma_producto_A, suma_producto_B, suma_producto_C)

2750 3090 3720


In [5]:
#Media de producto
media_producto_A = ventas_A.mean()
media_producto_B = ventas_B.mean()
media_producto_C = ventas_C.mean()

print(media_producto_A, media_producto_B, media_producto_C)

229.16666666666666 257.5 310.0


Paso 3: Manipulación y Análisis de Datos

Total de ventas por mes: Suma las ventas de los tres productos para cada mes.
Promedio de ventas por producto: Calcula el promedio de ventas por producto.
Mes con mayor y menor ventas: Identifica qué mes tuvo el total de ventas más alto y cuál el más bajo usando las funciones np.argmax y np.argmin.

In [6]:
suma = ventas_A+ventas_B+ventas_C
print(suma)

[ 530  630  720  810  770  770  740  780  860  910  990 1050]


In [7]:
promedio = suma / 3
print(promedio)

[176.66666667 210.         240.         270.         256.66666667
 256.66666667 246.66666667 260.         286.66666667 303.33333333
 330.         350.        ]


In [47]:
maximo_ventas = np.max(suma)
minimo_ventas = np.min(suma)

index_max = np.where(suma == maximo_ventas)
index_min = np.where(suma == minimo_ventas)


print(meses[index_max[0]])
print(meses[index_min[0]])


['Diciembre']
['Enero']


Paso 4: Operaciones Avanzadas con NumPy

Reshape y Transposición:

Crea una matriz 2D con las ventas de los tres productos y transforma su forma (reshape) a un array tridimensional con dimensiones (3, 4, 3).
Transpone la matriz de ventas para que las filas se conviertan en columnas.
Invertir arrays: Invierte las ventas de cada producto en orden de meses.
Aplanar la matriz: Convierte la matriz de ventas a un array unidimensional.

In [15]:
matriz_ventas = np.vstack((ventas_A, ventas_B,ventas_C))
print(matriz_ventas)


[[150 200 250 300 220 210 180 190 230 240 280 300]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [200 220 240 260 280 300 320 340 360 380 400 420]]


In [13]:
matriz_ventas_reshape = np.reshape(matriz_ventas, (3,4,3))
print(matriz_ventas_reshape)

[[[150 200 250]
  [300 220 210]
  [180 190 230]
  [240 280 300]]

 [[180 210 230]
  [250 270 260]
  [240 250 270]
  [290 310 330]]

 [[200 220 240]
  [260 280 300]
  [320 340 360]
  [380 400 420]]]


In [14]:
matriz_transpuesta = matriz_ventas.T
print(matriz_transpuesta)

[[150 180 200]
 [200 210 220]
 [250 230 240]
 [300 250 260]
 [220 270 280]
 [210 260 300]
 [180 240 320]
 [190 250 340]
 [230 270 360]
 [240 290 380]
 [280 310 400]
 [300 330 420]]


In [21]:
invertido_ventas_A = ventas_A[::-1] 
invertido_ventas_B = ventas_B[::-1]
invertido_ventas_C = ventas_C[::-1]

print(invertido_ventas_A)
print(invertido_ventas_B)
print(invertido_ventas_C)

[300 280 240 230 190 180 210 220 300 250 200 150]
[330 310 290 270 250 240 260 270 250 230 210 180]
[420 400 380 360 340 320 300 280 260 240 220 200]


In [29]:
matriz_aplanada = matriz_ventas.flatten()
print(matriz_aplanada)

[150 200 250 300 220 210 180 190 230 240 280 300 180 210 230 250 270 260
 240 250 270 290 310 330 200 220 240 260 280 300 320 340 360 380 400 420]


Paso 5: Análisis de Elementos Únicos

Utiliza np.unique para encontrar los elementos únicos en los datos de ventas y cuenta cuántas veces aparece cada uno.

In [ ]:
unique, counts = np.unique(matriz_ventas, return_counts=True)
dic={ int(unique[i]):int(counts[i]) for i in range(unique.__len__())}

print(dic)

{150: 1, 180: 2, 190: 1, 200: 2, 210: 2, 220: 2, 230: 2, 240: 3, 250: 3, 260: 2, 270: 2, 280: 2, 290: 1, 300: 3, 310: 1, 320: 1, 330: 1, 340: 1, 360: 1, 380: 1, 400: 1, 420: 1}


Paso 6: Indexación y Slicing

Ventas del primer trimestre: Extrae las ventas de los tres primeros meses del año.
Indexación booleana: Selecciona los meses donde el total de ventas de los tres productos supere los 800.
Selección avanzada: Usa una lista de índices para seleccionar las ventas de los meses pares (o selecciona los meses a tu elección) y muestra esas ventas en una nueva matriz.

In [ ]:
#Primer trimestre
primer_trimestre = suma[0:3]
print(primer_trimestre)

#Ventas más altas de 800
higher_eight_hundred = suma>800
print(higher_eight_hundred)

#Meses pares
even = np.array([i for i in range(1,13) if i%2==0] )
meses_pares = matriz_ventas[:,even-1]

print(meses_pares)
print(matriz_ventas)

[530 630 720]
[False False False  True False False False False  True  True  True  True]
[[200 300 210 190 240 300]
 [210 250 260 250 290 330]
 [220 260 300 340 380 420]]
[[150 200 250 300 220 210 180 190 230 240 280 300]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [200 220 240 260 280 300 320 340 360 380 400 420]]
