## Manipulación de Dimensiones en Arrays NumPy

In [29]:
import numpy as np

escalar = np.array(42)
print(type(escalar))



<class 'numpy.ndarray'>


Vectores

In [30]:
vector = np.array( [10, 20, 30, 40, 50] )
print(vector)

[10 20 30 40 50]


Matrices


In [31]:
matrix = np.array([[1,2,3,], [4,5,6,], [7, 8, 9]])
print(matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Tensores

In [32]:
tensor = np.array([[[1,2], [3,4], [5,6], [7,8], [9,10]]])
print(tensor)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]]


Imprimir un array de cierto rango

In [33]:
array_arange = np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


Matriz identidad 3x3

In [34]:
eye_matrix = np.eye(3)
print(eye_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Impprimir Diagonal

In [36]:
diag = np.diag([1, 2, 3, 4 , 5 ,6  ,7])
print(diag)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


Uso de random 

In [37]:
random = np.random.random([2, 3])
print(random)

[[0.13690874 0.18231777 0.93058576]
 [0.58974417 0.58243659 0.04446158]]


## Manipulación de Arrays NumPy para Análisis de Datos en Python


In [ ]:
array = np.array([[1,2,3], [4, 5, 6]])
print(array.ndim) #2
print(array.shape) #2, 3 - tamaño de la matriz
print(array.dtype) #int64 tipo de dato


2
(2, 3)
int64


In [50]:
# Array de enteros
int_array = np.array([1, 2, 3], dtype='int32')

# Array de flotantes
float_array = np.array([1.0, 2.0, 3.0], dtype='float32')

# Array de booleanos
bool_array = np.array([True, False, True], dtype='bool')

# Array de números complejos
complex_array = np.array([1+2j, 3+4j], dtype='complex64')

# Array de cadenas de texto
str_array = np.array(['a', 'b', 'c'], dtype='str')

z = np.array(3, dtype=np.uint8)
print(z)

3


In [44]:
double_array = np.array([1, 2 ,3], dtype='d')
print(double_array)

[1. 2. 3.]


In [46]:
z = z.astype(np.float64)
print(z)

3.0


Suma de arreglos

In [47]:
array = np.array([[1,2,3], [4, 5, 6]])
sum = np.sum(array)
print(sum)

21


Promedio

In [48]:
mean = np.mean(array)
print(mean)

3.5


Desviación estandar

In [49]:
std = np.std(array)
print(std)

1.707825127659933


## Indexación y Slicing en NumPy

In [51]:
array = np.array([10, 20, 30, 40, 50])
print(array[1])
print(array[-1])

20
50


In [ ]:
print(array[1:8]) 
#Si excede en los elementos, imprimira lo elementos del array.
#En este caso hasta el ídice 4.

[20 30 40 50]


In [55]:
array = np.array([10, 20, 30, 40, 50])
bool_index = array > 25
print(bool_index)
print(type(bool_index))


[False False  True  True  True]
<class 'numpy.ndarray'>


In [56]:
index = [2, 0, 3]
print(array[index])

[30 10 40]
